### ISSUE TITLE
图片内容错误？

### ISSUE THREAD

**Issue by abc767234318** [RangerNJU/Static-Program-Analysis-Book#14]
![image](https://user-images.githubusercontent.com/51507451/161225806-41f4fbcb-6cde-4c58-ae3e-5563218c9861.png)
这里这个B是不是应该改成S。下面这张图算法里才是对的吧。
![image](https://user-images.githubusercontent.com/51507451/161225916-908f5bce-d75d-4ff8-aaa1-7fd1aad9e894.png)

**Comment by RangerNJU** [comment]
是的。抽空仔细看了上下文，下面的截图是对的。稍后有空会改~
感谢捉虫！

**Comment by abc767234318** [comment]
@RangerNJU ok
