### ISSUE TITLE
The online gitbook service is down

### ISSUE THREAD

**Issue by itewqq** [RangerNJU/Static-Program-Analysis-Book#18]
![image](https://user-images.githubusercontent.com/30570177/220900124-a2914229-8486-465f-adcb-d3b88f695137.png)

**Comment by RangerNJU** [comment]
Domain expired. Will renew and update later this week.

**Comment by RangerNJU** [comment]
Should be able to access via [the link in the readme](https://ranger-nju.gitbook.io/static-program-analysis-book/) from now on.
