### ISSUE TITLE
提个小建议

### ISSUE THREAD

**Issue by enochii** [RangerNJU/Static-Program-Analysis-Book#7]
简介部分看起来好像有一些图片是摘自南大软件分析课程的，这个课程感觉也可以加在资料推荐中，课件和老师们讲得都很不错。

**Comment by RangerNJU** [comment]
确实是摘自南大的课程。
我在[这里](https://spa-book.pblo.gq/ch0/ch0/00-02-sources-and-license)也说明了本仓库的资料来源，故未在README中作为进一步学习资料记录。
